# Generated by Django 2.2 on 2019-10-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20191024_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(choices=[('not done', 'NOT DONE'), ('done', 'DONE')], default=True),
        ),
    ]
