# Generated by Django 2.2 on 2019-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20191024_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(choices=[(False, 'NOT DONE'), (True, 'DONE')], default=True),
        ),
    ]
